### ISSUE TITLE
add Friends

### ISSUE THREAD

**Issue by amalhajo** [TheIncredibles3445/ParkingApp#4]

**Comment by asgadabdallahabdallah1** [comment]
For the this week a i have been working on the user collection and friends sub collection
all the wrok have been done in app js and link screen.

all the features have been added:
- List of all the users
- Follow requests
- Accept request
-decline request
-remove friend
- My friends list
- Search bar

the friends is one of the big feature we have, in link screen there is a list of all the users
registered to the app with a button beside each (follow button) so if the current user want 
to follow one of the users what gonna happen is that, is the status of each one of them (the current user(status will be changed to 1: means pending) 
and the user that they want to follow (status will be changed to 2: means someone is trying to follow them)) when the status changes the title of the
button will be changed from "follow" to "requested" and the current user will be added to the "follow request" list of the other user.
for the other user: in the follow request it will show the list of the users the want to follow them + 2 button (accept+decline)+ 

when the user accept the follow its going to be removed from the follow requests and it will be added to "My Friends" list and the same user 
will be added the other user Friends list.(so now both are friends and they can share the location of each other(share location is not handeled yet)).
and after they added each other>> the list of people you may know will be changed and it will show all the users except my friends.

+a bug to be fixed is: (if one user followed someone and it changed to requested, other users are able to see the requested button)
[parking.zip](https://github.com/TheIncredibles3445/ParkingApp/files/4356775/parking.zip)

**Comment by asgadabdallahabdallah1** [comment]
20 March - 22 March
due to the bugs i had (if a user requested to follow another user all other users can see re request (because i was storing the status in the  user object itself)), 
so the only way to solve this issue is to rethought the whole processes of the friends feature
the idea now is:
scenario 1: if the A requested to follow B:
A will have a sub-collection called "My Requests" with B id and B will have sub collection called "Request" with A id

scenario 2:
the request that B have will show in the "Follow Requests" list 
if B accept A follow request >> its gonna be removed from A "My Request" sub collection and from B "Request"
sub collection + it will be removed from "Follow Requests" list and A will be added to B Friends sub collection and the same for B.

scenario 3: 
if B declined the request it will also be removed from  the "Request" sub collection and "My Request" sub collection
same scenario if B accepted the request and removed A after from the "My Friends" List


[friends-update.zip](https://github.com/TheIncredibles3445/ParkingApp/files/4380673/friends-update.zip)
